version: "3.8"
services:
  angular-app:
    image: node:20-alpine3.16
    ports:
      - 4200:4200
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
